=== vampaz/tech-radar-generator/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/dprgarner/tech-radar-generator/master/schema.json",
  "type": "object",
  "title": "Radar",
  "description": "The schema for the tech-radar-generator data.",
  "properties": {
    "title": {
      "type": "string",
      "description": "The title of the radar, which appears in the page title and the header of the page"
    },
    "quadrants": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "An array of exactly four quadrant names in the radar, rendered anti-clockwise from the top-right",
      "minItems": 4,
      "maxItems": 4
    },
    "rings": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "An array of up to four names of rings in the radar, from inner-most to outer-most",
      "minItems": 1,
      "maxItems": 4
    },
    "blips": {
      "type": "array",
      "description": "An array of _blip_ objects determining the items appearing on the radar",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the blip"
          },
          "quadrant": {
            "type": "string",
            "description": "The quadrant of the radar that the blip appears in. There should be exactly four different quadrants in the full list of blips."
          },
          "ring": {
            "type": "string",
            "description": "The ring of the radar that the blip should appear in. This must take one of the provided ring values."
          },
          "isNew": {
            "type": "boolean",
            "description": "Set to true if the blip has been created or modified recently"
          },
          "description": {
            "type": "string",
            "description": "A short description of the blip which appears when the blip is selected in the radar. This field can include HTML, and should include links to any supporting information or resources about the blip, and an explanation of why it's classified in the current ring."
          }
        },
        "required": ["name", "quadrant", "ring", "isNew", "description"],
        "additionalProperties": false
      }
    }
  },
  "required": ["title", "quadrants", "rings", "blips"],
  "additionalProperties": false
}

=== vampaz/tech-radar-generator/example-data.json
{
  "title": "Everon Tech radar",
  "quadrants": [
    "Languages and Frameworks",
    "Techniques",
    "Tools",
    "Platforms"
  ],
  "rings": [
    "ADOPT",
    "TRIAL",
    "ASSESS",
    "HOLD"
  ],
  "blips": [
    {
      "description" : "Used by <i>Schumis</i>.<br/><br/>The Adyen API Library for Java enables you to work with Adyen APIs and Hosted Payment Pages.",
      "ring" : "ADOPT",
      "quadrant" : "Languages and Frameworks",
      "name" : "Adyen library",
      "isNew" : false
    },
    {
      "quadrant" : "Languages and Frameworks",
      "name" : "Angular.js",
      "isNew" : false,
      "ring" : "HOLD",
      "description" : "Used by <i>Tenant Portal, Black Hole</i>.<br/><br/>AngularJS is a toolset for building the framework most suited to your application development. It is fully extensible and works well with other libraries. Every feature can be modified or replaced to suit your unique development workflow and feature needs. Read on to find out how."
    },
    {
      "name" : "Apache HTTP Client 4",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false,
      "ring" : "ADOPT",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>https://hc.apache.org/httpcomponents-client-ga/"
    },
    {
      "quadrant" : "Languages and Frameworks",
      "name" : "Apache Shiro",
      "isNew" : false,
      "description" : "Used by <i>Moonsters, Sputnik</i>.<br/><br/>Apache Shiro is an open source software security framework that performs authentication, authorization, cryptography and session management. Shiro has been designed to be an intuitive and easy-to-use framework while still providing robust security features.",
      "ring" : "HOLD"
    },
    {
      "isNew" : false,
      "name" : "ArchUnit",
      "quadrant" : "Languages and Frameworks",
      "ring" : "TRIAL",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>ArchUnit is a free, simple and extensible library for checking the architecture of your Java code."
    },
    {
      "quadrant" : "Languages and Frameworks",
      "name" : "AssertJ",
      "isNew" : false,
      "ring" : "ADOPT",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>AssertJ is a java library providing a rich set of assertions, truly helpful error messages, improves test code readability and is designed to be super easy to use within your favorite IDE."
    },
    {
      "quadrant" : "Languages and Frameworks",
      "name" : "Bascss",
      "isNew" : false,
      "ring" : "HOLD",
      "description" : "Used by <i>Tenant Portal, Black Hole</i>.<br/><br/>Basscss is a lightweight collection of base element styles and immutable utilities designed for speed, clarity, performance, and scalability."
    },
    {
      "name" : "Bash",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false,
      "ring" : "ADOPT",
      "description" : "Used by <i>42, Rocket</i>.<br/><br/>Well, bash, you know."
    },
    {
      "description" : "Used by <i>Schumis</i>.<br/><br/>Carthage is intended to be the simplest way to add frameworks to your Cocoa application.",
      "ring" : "ADOPT",
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Carthage"
    },
    {
      "ring" : "ADOPT",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>Commons CSV reads and writes files in variations of the Comma Separated Value (CSV) format.",
      "isNew" : false,
      "name" : "Common-csv",
      "quadrant" : "Languages and Frameworks"
    },
    {
      "ring" : "TRIAL",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>Feign makes writing java http clients easier",
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Feign"
    },
    {
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "GCP SDK",
      "ring" : "ADOPT",
      "description" : "Used by <i>Sputnik, Moonsters</i>.<br/><br/>Tools and libraries for interacting with Google Cloud products and services."
    },
    {
      "description" : "Used by <i>42</i>.<br/><br/>Go is a statically typed, compiled programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson. Go is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency.",
      "ring" : "ADOPT",
      "quadrant" : "Languages and Frameworks",
      "name" : "Golang",
      "isNew" : false
    },
    {
      "isNew" : false,
      "name" : "Google Address Validation",
      "quadrant" : "Languages and Frameworks",
      "ring" : "ADOPT",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>?"
    },
    {
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "GraphQL",
      "ring" : "ASSESS",
      "description" : "Used by <i>42</i>.<br/><br/>GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data. "
    },
    {
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Groovy",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>Apache Groovy is a Java-syntax-compatible object-oriented programming language for the Java platform. ",
      "ring" : "ADOPT"
    },
    {
      "name" : "Guava",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false,
      "description" : "Used by <i>Sputnik,Sputnik</i>.<br/><br/>Google Guava is an open-source set of common libraries for Java, mainly developed by Google engineers.",
      "ring" : "HOLD"
    },
    {
      "description" : "Used by <i>Sputnik, Moonsters, Orion</i>.<br/><br/>Google Guice (pronounced \"juice\") is an open-source software framework for the Java platform released by Google under the Apache License. It provides support for dependency injection using annotations to configure Java objects",
      "ring" : "HOLD",
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Guice"
    },
    {
      "description" : "Used by <i>Sputnik</i>.<br/><br/>Junit Matchers that can be combined to create flexible expressions of intent",
      "ring" : "ADOPT",
      "quadrant" : "Languages and Frameworks",
      "name" : "Hamcrest",
      "isNew" : false
    },
    {
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Hibernate Bean Validation",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>Hibernate Validator allows to express and validate application constraints. The default metadata source are annotations, with the ability to override and extend through the use of XML. ",
      "ring" : "ADOPT"
    },
    {
      "description" : "Used by <i>Sirius, Sputnik, Perseus</i>.<br/><br/>Hibernate ORM enables developers to more easily write applications whose data outlives the application process. As an Object/Relational Mapping (ORM) framework, Hibernate is concerned with data persistence as it applies to relational databases (via JDBC).",
      "ring" : "ADOPT",
      "isNew" : false,
      "name" : "Hibernate ORM",
      "quadrant" : "Languages and Frameworks"
    },
    {
      "isNew" : false,
      "name" : "HikariCP",
      "quadrant" : "Languages and Frameworks",
      "description" : "Used by <i>Sputnik</i>.<br/><br/>HikariCP is a \"zero-overhead\" production ready JDBC connection pool. ",
      "ring" : "ADOPT"
    },
    {
      "description" : "Used by <i>Sputnik</i>.<br/><br/>Jackson is a high-performance JSON processor for Java.",
      "ring" : "ADOPT",
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Jackson"
    },
    {
      "name" : "Java 11",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false,
      "description" : "Used by <i>Orion, Sirius, Hubble, Ozone, Sputnik, Perseus</i>.<br/><br/>https://openjdk.java.net/projects/jdk/11/",
      "ring" : "ADOPT"
    },
    {
      "name" : "Java 8",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false,
      "ring" : "HOLD",
      "description" : "Used by <i>Sputnik, Ozone</i>.<br/><br/>https://www.oracle.com/java/technologies/java8.html"
    },
    {
      "description" : "Used by <i>Black Hole</i>.<br/><br/>JavaScript is the best, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification. JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.",
      "ring" : "ADOPT",
      "name" : "JavaScript",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false
    },
    {
      "description" : "Used by <i>Moonsters</i>.<br/><br/>Jakarta RESTful Web Services, is a Jakarta EE API specification that provides support in creating web services according to the Representational State Transfer architectural pattern. JAX-RS uses annotations, introduced in Java SE 5, to simplify the development and deployment of web service clients and endpoints.",
      "ring" : "HOLD",
      "isNew" : false,
      "quadrant" : "Languages and Frameworks",
      "name" : "Jax-rs"
    },
    {
      "name" : "Jersey",
      "quadrant" : "Languages and Frameworks",
      "isNew" : false,
      "description" : "Used by <i>Sputnik, Moonsters, Orion</i>.<br/><br/>Jersey RESTful Web Services, formerly Glassfish Jersey, currently Eclipse Jersey framework is an open source framework for developing RESTful Web Services in Java. It provides support for JAX-RS APIs and serves as a JAX-RS Reference Implementation.",
      "ring" : "HOLD"
    },
    {
      "description" : "Used by <i>Black Hole</i>.<br/><br/>Jest is a JavaScript testing framework designed to ensure correctness of any JavaScript codebase. ",
      "ring" : "ADOPT",
      "quadrant" : "Languages and Frameworks",
      "name" : "Jest",
      "isNew" : false
    },
    {
